### ISSUE TITLE
Arch Linux (Antergos), HP 17-j141nr 

### ISSUE THREAD

**Issue by labdocodigo** [payden/libfprint#7]
Hello,

Fiest off all, thanks for the great work that you are doing.
I tried to compile this repo and install Fingerprint-gui from the AUR.
After install nothing happens when i open fingerprint-gui -d.

How do i start here? Im not that good with linux...

Thanks.

**Comment by lab-do-codigo** [comment]
I compiled with this command:
./autogen.sh && ./configure -C --quiet && make && sudo make install

**Comment by lab-do-codigo** [comment]
This is the log:

[lab@Lab Downloads]$ cd libfprint/
[lab@Lab libfprint]$ ./autogen.sh && ./configure -C --quiet && make && sudo make install
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:11: installing './compile'
configure.ac:2: installing './missing'
examples/Makefile.am: installing './depcomp'
configure: WARNING: unrecognized options: --enable-maintainer-mode
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for inline... inline
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBUSB... yes
checking for CRYPTO... yes
checking for GLIB... yes
configure: installing udev rules in /usr/lib/udev/rules.d
checking for IMAGING... yes
checking for Xv extensions... yes
configure: ** Using pixman for imaging
configure: ** vfs0050 driver enabled
configure: ** upekts driver enabled
configure:    upeke2 driver disabled
configure: ** upektc driver enabled
configure: ** upeksonly driver enabled
configure: ** vcom5s driver enabled
configure: ** uru4000 driver enabled
configure:    fdu2000 driver disabled
configure: ** aes1610 driver enabled
configure: ** aes1660 driver enabled
configure: ** aes2501 driver enabled
configure: ** aes2550/aes2810 driver enabled
configure: ** aes2660 driver enabled
configure: ** aes3500 driver enabled
configure: ** aes4000 driver enabled
configure: ** vfs101 driver enabled
configure: ** vfs301 driver enabled
configure: ** upektc_img driver enabled
configure: ** etes603 driver enabled
configure: ** aeslib helper functions enabled
configure: ** aesX660 common routines enabled
configure: ** aes3k common routines enabled
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libfprint.pc
config.status: creating Makefile
config.status: creating libfprint/Makefile
config.status: creating examples/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --enable-maintainer-mode
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/lab/Downloads/libfprint/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '/home/lab/Downloads/libfprint'
Making all in libfprint
make[2]: Entering directory '/home/lab/Downloads/libfprint/libfprint'
  CC       libfprint_la-async.lo
  CC       libfprint_la-core.lo
  CC       libfprint_la-data.lo
  CC       libfprint_la-drv.lo
  CC       libfprint_la-img.lo
  CC       libfprint_la-imgdev.lo
  CC       libfprint_la-poll.lo
  CC       libfprint_la-sync.lo
  CC       drivers/libfprint_la-upekts.lo
  CC       drivers/libfprint_la-upeksonly.lo
  CC       drivers/libfprint_la-upektc.lo
  CC       drivers/libfprint_la-uru4000.lo
  CC       drivers/libfprint_la-vcom5s.lo
  CC       drivers/libfprint_la-aes1610.lo
  CC       drivers/libfprint_la-aes1660.lo
  CC       drivers/libfprint_la-aes2501.lo
  CC       drivers/libfprint_la-aes2550.lo
  CC       drivers/libfprint_la-aes2660.lo
  CC       drivers/libfprint_la-aes3500.lo
  CC       drivers/libfprint_la-aes4000.lo
  CC       drivers/libfprint_la-vfs101.lo
  CC       drivers/libfprint_la-vfs301.lo
  CC       drivers/libfprint_la-upektc_img.lo
  CC       drivers/libfprint_la-etes603.lo
  CC       drivers/libfprint_la-vfs0050.lo
drivers/vfs0050.c: In function ‘process_image_data’:
drivers/vfs0050.c:42:30: warning: unused variable ‘diff’ [-Wunused-variable]
     int i, x, sum, last_sum, diff;
                              ^
drivers/vfs0050.c:42:20: warning: unused variable ‘last_sum’ [-Wunused-variable]
     int i, x, sum, last_sum, diff;
                    ^
drivers/vfs0050.c:42:15: warning: unused variable ‘sum’ [-Wunused-variable]
     int i, x, sum, last_sum, diff;
               ^
drivers/vfs0050.c:42:12: warning: unused variable ‘x’ [-Wunused-variable]
     int i, x, sum, last_sum, diff;
            ^
drivers/vfs0050.c:39:33: warning: variable ‘calibration_line’ set but not used [-Wunused-but-set-variable]
     struct vfs0050_line *line, *calibration_line;
                                 ^
drivers/vfs0050.c: In function ‘submit_image’:
drivers/vfs0050.c:108:25: warning: unused variable ‘vfs_dev’ [-Wunused-variable]
     struct vfs0050_dev *vfs_dev = dev->priv;
                         ^
drivers/vfs0050.c: In function ‘tmp_writeout_buf’:
drivers/vfs0050.c:98:46: warning: iteration 100u invokes undefined behavior [-Waggressive-loop-optimizations]
             sprintf(tmpbuf, "%d\t", line->row[x] & 0xff);
                                              ^
drivers/vfs0050.c:97:9: note: containing loop
         for (x = 0; x < VFS0050_IMG_WIDTH + 32; x++) {
         ^
  CC       libfprint_la-pixman.lo
  CC       libfprint_la-aeslib.lo
  CC       drivers/libfprint_la-aesx660.lo
  CC       drivers/libfprint_la-aes3k.lo
  CC       nbis/mindtct/libfprint_la-binar.lo
  CC       nbis/mindtct/libfprint_la-block.lo
  CC       nbis/mindtct/libfprint_la-contour.lo
  CC       nbis/mindtct/libfprint_la-detect.lo
  CC       nbis/mindtct/libfprint_la-dft.lo
  CC       nbis/mindtct/libfprint_la-free.lo
  CC       nbis/mindtct/libfprint_la-globals.lo
  CC       nbis/mindtct/libfprint_la-imgutil.lo
  CC       nbis/mindtct/libfprint_la-init.lo
  CC       nbis/mindtct/libfprint_la-line.lo
  CC       nbis/mindtct/libfprint_la-loop.lo
  CC       nbis/mindtct/libfprint_la-maps.lo
  CC       nbis/mindtct/libfprint_la-matchpat.lo
  CC       nbis/mindtct/libfprint_la-minutia.lo
  CC       nbis/mindtct/libfprint_la-quality.lo
  CC       nbis/mindtct/libfprint_la-remove.lo
  CC       nbis/mindtct/libfprint_la-ridges.lo
  CC       nbis/mindtct/libfprint_la-shape.lo
  CC       nbis/mindtct/libfprint_la-sort.lo
  CC       nbis/mindtct/libfprint_la-util.lo
  CCLD     libfprint.la
  CC       fprint_list_udev_rules-fprint-list-udev-rules.o
  CCLD     fprint-list-udev-rules
./fprint-list-udev-rules > 60-fprint-autosuspend.rules
make[2]: Leaving directory '/home/lab/Downloads/libfprint/libfprint'
Making all in doc
make[2]: Entering directory '/home/lab/Downloads/libfprint/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lab/Downloads/libfprint/doc'
make[2]: Entering directory '/home/lab/Downloads/libfprint'
make[2]: Leaving directory '/home/lab/Downloads/libfprint'
make[1]: Leaving directory '/home/lab/Downloads/libfprint'
[sudo] senha para lab: 
Making install in libfprint
make[1]: Entering directory '/home/lab/Downloads/libfprint/libfprint'
make[2]: Entering directory '/home/lab/Downloads/libfprint/libfprint'
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libfprint.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libfprint.so.0.0.0 /usr/local/lib/libfprint.so.0.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libfprint.so.0.0.0 libfprint.so.0 || { rm -f libfprint.so.0 && ln -s libfprint.so.0.0.0 libfprint.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libfprint.so.0.0.0 libfprint.so || { rm -f libfprint.so && ln -s libfprint.so.0.0.0 libfprint.so; }; })
libtool: install: /usr/bin/install -c .libs/libfprint.lai /usr/local/lib/libfprint.la
libtool: install: /usr/bin/install -c .libs/libfprint.a /usr/local/lib/libfprint.a
libtool: install: chmod 644 /usr/local/lib/libfprint.a
libtool: install: ranlib /usr/local/lib/libfprint.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/usr/local/include/libfprint'
 /usr/bin/install -c -m 644 fprint.h '/usr/local/include/libfprint'
 /usr/bin/mkdir -p '/usr/lib/udev/rules.d'
 /usr/bin/install -c -m 644 60-fprint-autosuspend.rules '/usr/lib/udev/rules.d'
make[2]: Leaving directory '/home/lab/Downloads/libfprint/libfprint'
make[1]: Leaving directory '/home/lab/Downloads/libfprint/libfprint'
Making install in doc
make[1]: Entering directory '/home/lab/Downloads/libfprint/doc'
make[2]: Entering directory '/home/lab/Downloads/libfprint/doc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/lab/Downloads/libfprint/doc'
make[1]: Leaving directory '/home/lab/Downloads/libfprint/doc'
make[1]: Entering directory '/home/lab/Downloads/libfprint'
make[2]: Entering directory '/home/lab/Downloads/libfprint'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libfprint.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/lab/Downloads/libfprint'
make[1]: Leaving directory '/home/lab/Downloads/libfprint'
[lab@Lab libfprint]$
